name: Deploy Project

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET: sandwich-user-projects
  USER_ID: ${{ secrets.USER_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  ECS_CONTAINER_NAME: "app-container"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Node가 필요없는 정적 리포여도 문제 없음
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # package.json 있으면 설치 + build 스크립트가 있을 때만 빌드
      - name: Build (if needed)
        run: |
          if [ -f package.json ]; then
            npm ci
            if npm run | grep -q " build"; then
              npm run build || true
            fi
          fi

      # 배포 소스 폴더 자동 감지: build -> dist -> out -> (없으면) .
      - name: Pick deploy dir (build/dist/out or .)
        id: pick
        run: |
          for d in build dist out; do
            if [ -d "$d" ]; then
              echo "dir=$d" >> $GITHUB_OUTPUT
              echo "Detected deploy dir: $d"
              exit 0
            fi
          done
          echo "dir=." >> $GITHUB_OUTPUT
          echo "No build/dist/out found, deploying repository root (static files)."

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.SANDWICH_USER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SANDWICH_USER_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # (선택) 추가 파일 동기화: s3://.../deploy/ -> ./additional/
      - name: Download additional files from S3
        run: |
          mkdir -p additional
          aws s3 sync "s3://${{ env.S3_BUCKET }}/${{ env.USER_ID }}/${{ env.PROJECT_ID }}/deploy/" additional/ || true

      # 아래 ECS/ECR 단계는 Dockerfile 있을 때만 이미지 푸시 (리포 정의/서비스 생성은 실패해도 무시)
      - name: Create ECS Cluster
        run: |
          aws ecs create-cluster --cluster-name sandwich-${{ github.repository_owner }}-${{ github.event.repository.name }} || true

      - name: Create ECS Service
        run: |
          aws ecs create-service \
            --cluster sandwich-${{ github.repository_owner }}-${{ github.event.repository.name }} \
            --service-name sandwich-${{ github.repository_owner }}-${{ github.event.repository.name }} \
            --task-definition sandwich-${{ github.repository_owner }}-${{ github.event.repository.name }} \
            --desired-count 1 \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[subnet-0c63ddf51361003c7],securityGroups=[sg-05757f4e3849d99cf],assignPublicIp=ENABLED}" || true

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-names "sandwich-user-projects/${{ env.USER_ID }}-${{ env.PROJECT_ID }}" || \
          aws ecr create-repository --repository-name "sandwich-user-projects/${{ env.USER_ID }}-${{ env.PROJECT_ID }}"

      - name: Build and Push Docker image (only if Dockerfile exists)
        run: |
          if [ -f Dockerfile ]; then
            IMAGE_TAG=${GITHUB_SHA}
            ECR_URI=398808282696.dkr.ecr.ap-northeast-2.amazonaws.com/sandwich-user-projects/${{ env.USER_ID }}-${{ env.PROJECT_ID }}
            docker build -t $ECR_URI:$IMAGE_TAG .
            docker push $ECR_URI:$IMAGE_TAG
            docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest
            docker push $ECR_URI:latest
            echo "[{\"name\": \"${{ env.ECS_CONTAINER_NAME }}\", \"imageUri\": \"$ECR_URI:$IMAGE_TAG\"}]" > imagedefinitions.json
          else
            echo "No Dockerfile, skipping Docker build"
          fi

      # 자동 감지한 폴더를 S3로 업로드
      - name: Deploy to S3
        run: |
          SRC="${{ steps.pick.outputs.dir }}"
          if [ "$SRC" = "." ]; then
            aws s3 sync . "s3://${{ env.S3_BUCKET }}/${{ env.USER_ID }}/${{ env.PROJECT_ID }}/" \
              --exclude ".git/*" --exclude ".github/*" --exclude "node_modules/*"
          else
            aws s3 sync "$SRC/" "s3://${{ env.S3_BUCKET }}/${{ env.USER_ID }}/${{ env.PROJECT_ID }}/" --delete
          fi

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.SANDWICH_USER_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/${{ env.USER_ID }}/${{ env.PROJECT_ID }}/*"
